source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FitTrack_Example', :exclusive => true do
  pod 'FitTrack', :path => '../'
  
end

target 'FitTrack_Tests', :exclusive => true do
  pod 'FitTrack', :path => '../'
  
end

